// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCP.Server.DataAccess;

namespace PCP.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PCP.Shared.Models.Area", b =>
                {
                    b.Property<int?>("CG_AREA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CG_CIA")
                        .HasColumnType("int");

                    b.Property<int?>("CG_PROVE")
                        .HasColumnType("int");

                    b.Property<int?>("CG_TIPOAREA")
                        .HasColumnType("int");

                    b.Property<string>("DES_AREA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CG_AREA");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("PCP.Shared.Models.CalendarioFestivos", b =>
                {
                    b.Property<decimal>("Registro")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Registro");

                    b.ToTable("CalendarioFestivos");
                });

            modelBuilder.Entity("PCP.Shared.Models.CategoriaOperario", b =>
                {
                    b.Property<int?>("CG_CATEOP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CG_CIA")
                        .HasColumnType("int");

                    b.Property<string>("DES_CATEOP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MONEDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("VALOR_HORA")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("CG_CATEOP");

                    b.ToTable("CateOperario");
                });

            modelBuilder.Entity("PCP.Shared.Models.Celda", b =>
                {
                    b.Property<string>("CG_CELDA")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("AIRE_COMP")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CANT_ANOS")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("CANT_UNID")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("CG_AREA")
                        .HasColumnType("int");

                    b.Property<int?>("CG_CATEOP")
                        .HasColumnType("int");

                    b.Property<int?>("CG_CIA")
                        .HasColumnType("int");

                    b.Property<int?>("CG_DEPOSM")
                        .HasColumnType("int");

                    b.Property<int>("CG_PROVE")
                        .HasColumnType("int");

                    b.Property<int?>("CG_TIPOCELDA")
                        .HasColumnType("int");

                    b.Property<decimal?>("COEFI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("COMBUST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DES_CELDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ENERGIA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ILIMITADA")
                        .HasColumnType("int");

                    b.Property<decimal?>("M2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MONEDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("REP_ANOS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VALOR_AMOR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VALOR_MERC")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CG_CELDA");

                    b.ToTable("Celdas");
                });

            modelBuilder.Entity("PCP.Shared.Models.Cliente", b =>
                {
                    b.Property<int>("CG_CLI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DES_CLI")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CG_CLI");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PCP.Shared.Models.Compañia", b =>
                {
                    b.Property<int?>("CG_CIA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ACTIVIDAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVISO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COD_POST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES_CIA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES_PAIS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES_PROV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOM_COM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOM_FISC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FE_CIERRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FE_CONTRAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("IIBB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOC_COM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOC_FISC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PREFIJO")
                        .HasColumnType("int");

                    b.Property<string>("TELEFONO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CG_CIA");

                    b.ToTable("Cia");
                });

            modelBuilder.Entity("PCP.Shared.Models.Deposito", b =>
                {
                    b.Property<int>("CG_DEP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CG_CIA")
                        .HasColumnType("int");

                    b.Property<int?>("CG_CLI")
                        .HasColumnType("int");

                    b.Property<int?>("CG_PROVE")
                        .HasColumnType("int");

                    b.Property<string>("DES_DEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPO_DEP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CG_DEP");

                    b.ToTable("Depos");
                });

            modelBuilder.Entity("PCP.Shared.Models.Pedidos", b =>
                {
                    b.Property<decimal>("REGISTRO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ALTURA")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("ANCHO")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("AVISO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BONIFIC")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("CAMPANA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CANTENT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CANTENTA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CANTPED")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CG_ART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CG_ART1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CG_BARRAS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CG_CATEG")
                        .HasColumnType("int");

                    b.Property<int>("CG_CIA")
                        .HasColumnType("int");

                    b.Property<int>("CG_CLI")
                        .HasColumnType("int");

                    b.Property<int>("CG_COBR")
                        .HasColumnType("int");

                    b.Property<int>("CG_COMP")
                        .HasColumnType("int");

                    b.Property<string>("CG_COND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CG_COS")
                        .HasColumnType("int");

                    b.Property<decimal>("CG_CUENT")
                        .HasColumnType("decimal(15,0)");

                    b.Property<decimal>("CG_DEN")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CG_DEP")
                        .HasColumnType("int");

                    b.Property<int>("CG_EXPORT")
                        .HasColumnType("int");

                    b.Property<int>("CG_EXPRESO")
                        .HasColumnType("int");

                    b.Property<int>("CG_FORM_VENTAS")
                        .HasColumnType("int");

                    b.Property<int>("CG_IMPORT")
                        .HasColumnType("int");

                    b.Property<int>("CG_ORDEN")
                        .HasColumnType("int");

                    b.Property<decimal>("CG_ORDF")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("CG_ORDING")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("CG_PALLET")
                        .HasColumnType("int");

                    b.Property<string>("CG_POSTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CG_PROVE")
                        .HasColumnType("int");

                    b.Property<int>("CG_PROY")
                        .HasColumnType("int");

                    b.Property<int>("CG_TIRE")
                        .HasColumnType("int");

                    b.Property<int>("CG_TRANS")
                        .HasColumnType("int");

                    b.Property<int>("CG_VEN")
                        .HasColumnType("int");

                    b.Property<int>("CG_VEND")
                        .HasColumnType("int");

                    b.Property<string>("CG_ZONA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMPROB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONDVEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONDVENEX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONVMON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CRGO")
                        .HasColumnType("bit");

                    b.Property<string>("CUIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DESCUENTO")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("DESPACHO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES_ART")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES_ART1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES_CLI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DFF")
                        .HasColumnType("int");

                    b.Property<string>("DIRECC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIRENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DPP")
                        .HasColumnType("int");

                    b.Property<bool>("ENTRANSITO")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ENTRREAL")
                        .HasColumnType("datetime2");

                    b.Property<string>("FACTURA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FE_FAC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_MOV")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<int>("FLAG")
                        .HasColumnType("int");

                    b.Property<decimal>("IMPORTE1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("IMPORTE2")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(37,8)");

                    b.Property<decimal>("IMPORTE3")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(38,6)");

                    b.Property<decimal>("IMPORTE4")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(38,6)");

                    b.Property<decimal>("IMPORTE6")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("IMPRESO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("LARGO")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("LEYENDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCALIDAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOTE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MONEDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NETONOG")
                        .HasColumnType("bit");

                    b.Property<int>("NUMREQ")
                        .HasColumnType("int");

                    b.Property<decimal>("OBRA")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("OBS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBS3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBS4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBSERITEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBSERVACIONES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OCOMPRA")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("ORCO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PALLET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PEDIDO")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("PEDIDON")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("PEDIDOX")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("POSARAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PRESUP")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("PROFORMA")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("REGCOMPR")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("REMITO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SERIE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("STOCK")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("STOCKA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TIPOO")
                        .HasColumnType("int");

                    b.Property<string>("TIPO_FAC_AGRO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UBICACION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNIDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USUARIO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VALE")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("VALE_DESCA")
                        .HasColumnType("int");

                    b.Property<decimal>("VA_INDIC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VOUCHER")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("REGISTRO");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("PCP.Shared.Models.Producto", b =>
                {
                    b.Property<string>("CG_PROD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CAMPOCOM1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CANT_CAJA")
                        .HasColumnType("int");

                    b.Property<string>("CERFAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CG_ACTIVO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CG_AREA")
                        .HasColumnType("int");

                    b.Property<string>("CG_CELDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CG_CIA")
                        .HasColumnType("int");

                    b.Property<int>("CG_CLAS")
                        .HasColumnType("int");

                    b.Property<int>("CG_COS")
                        .HasColumnType("int");

                    b.Property<decimal>("CG_CUENT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CG_DENSEG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CG_DEPOSM")
                        .HasColumnType("int");

                    b.Property<int>("CG_EST")
                        .HasColumnType("int");

                    b.Property<int>("CG_FORM")
                        .HasColumnType("int");

                    b.Property<int>("CG_LINEA")
                        .HasColumnType("int");

                    b.Property<int>("CG_ORDEN")
                        .HasColumnType("int");

                    b.Property<string>("CG_PRODCLI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CG_TIPOAREA")
                        .HasColumnType("int");

                    b.Property<decimal>("COSTO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("COSTOTER")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("COSTOUC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("COSTOUC1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DESPLANO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES_PROD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DIAS")
                        .HasColumnType("int");

                    b.Property<string>("ESPECIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EXIGEDESPACHO")
                        .HasColumnType("bit");

                    b.Property<bool>("EXIGELOTE")
                        .HasColumnType("bit");

                    b.Property<bool>("EXIGESERIE")
                        .HasColumnType("bit");

                    b.Property<bool>("ExigeOA")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FE_UC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FE_UMA_ACT")
                        .HasColumnType("datetime2");

                    b.Property<string>("LINEA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LOPTIMO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LOTEVALOR1")
                        .HasColumnType("int");

                    b.Property<int>("LOTEVALOR2")
                        .HasColumnType("int");

                    b.Property<decimal>("MERMA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MONEDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MONEDAUC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NORMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NROPLANO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PENDIENTE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PER_GTIA")
                        .HasColumnType("int");

                    b.Property<decimal>("PESO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("POSARAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PPEDIDO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PROYECTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SETUP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("STOCKMIN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TIEMPOFAB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TIPO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UBICACION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UNIDEQUI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UNIDPESO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNIDSEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WEB")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CG_PROD");

                    b.ToTable("Prod");
                });

            modelBuilder.Entity("PCP.Shared.Models.Programa", b =>
                {
                    b.Property<decimal>("REGISTRO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ANIO")
                        .HasColumnType("int");

                    b.Property<string>("CAMPOCOM1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMPOCOM2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CANT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CANTFAB")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CANTORD")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CG_ANT")
                        .HasColumnType("int");

                    b.Property<int>("CG_AREA")
                        .HasColumnType("int");

                    b.Property<string>("CG_CELDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CG_CLAS")
                        .HasColumnType("int");

                    b.Property<int>("CG_CLI")
                        .HasColumnType("int");

                    b.Property<int>("CG_CONF")
                        .HasColumnType("int");

                    b.Property<decimal>("CG_CONFASOC")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("CG_DEPOSM")
                        .HasColumnType("int");

                    b.Property<int>("CG_ESTADO")
                        .HasColumnType("int");

                    b.Property<int>("CG_ESTADOCARGA")
                        .HasColumnType("int");

                    b.Property<int>("CG_ESTADOPREPARACION")
                        .HasColumnType("int");

                    b.Property<int>("CG_FLAG")
                        .HasColumnType("int");

                    b.Property<int>("CG_FORM")
                        .HasColumnType("int");

                    b.Property<int>("CG_NOCONF")
                        .HasColumnType("int");

                    b.Property<int>("CG_NOV")
                        .HasColumnType("int");

                    b.Property<int>("CG_ORDEN")
                        .HasColumnType("int");

                    b.Property<decimal>("CG_ORDF")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("CG_ORDFASOC")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("CG_ORDFORIG")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("CG_PROD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CG_PROG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CG_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CG_REG")
                        .HasColumnType("int");

                    b.Property<int>("Cg_Cia")
                        .HasColumnType("int");

                    b.Property<int>("Cg_Prove")
                        .HasColumnType("int");

                    b.Property<string>("DES_PROD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DIASFAB")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DISFAB")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Etiqueta")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FECHA_INICIO_REAL_FABRICACION")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FECHA_PREVISTA_FABRICACION")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_ANUL")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_CIERRE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_CONF")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_CURSO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_EMIT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_ENTREGA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_FIRME")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_ORDF")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_PLAN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_PLANTA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_PROG")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FE_REG")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fe_Audit")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HORASFAB")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("HS_FINPREPARACION")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HS_INICIOPREPARACION")
                        .HasColumnType("datetime2");

                    b.Property<string>("HS_ORDF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("INSUMOS_ENTREGADOS_A_PLANTA")
                        .HasColumnType("bit");

                    b.Property<string>("LINEA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MERMA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MINFAB")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("NREGISTRO")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("OBSERSECUEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBSERV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ORCO")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("ORDEN")
                        .HasColumnType("int");

                    b.Property<int>("PARTIDA")
                        .HasColumnType("int");

                    b.Property<decimal>("PEDIDO")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("PROCESO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESERVA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SEGFAB")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SEMANA")
                        .HasColumnType("int");

                    b.Property<int>("SEM_ABAST")
                        .HasColumnType("int");

                    b.Property<int>("SEM_ABAST_PURO")
                        .HasColumnType("int");

                    b.Property<int>("SEM_ORIGEN")
                        .HasColumnType("int");

                    b.Property<decimal>("TIEMPOSECUEN")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("USUARIO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("REGISTRO");

                    b.ToTable("Programa");
                });

            modelBuilder.Entity("PCP.Shared.Models.Provincia", b =>
                {
                    b.Property<int>("CG_PROV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DES_PROV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CG_PROV");

                    b.ToTable("Prov");
                });

            modelBuilder.Entity("PCP.Shared.Models.Unidad", b =>
                {
                    b.Property<string>("UNID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CG_CIA")
                        .HasColumnType("int");

                    b.Property<decimal>("CG_DENBASICA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CODIGO")
                        .HasColumnType("decimal(2,0)");

                    b.Property<string>("DES_UNID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPOUNID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UNID");

                    b.ToTable("Unidades");
                });
#pragma warning restore 612, 618
        }
    }
}
